import { DatabaseSync } from "node:sqlite";
import { createHash, randomUUID } from "node:crypto";
import { mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { basename, dirname, extname, join, resolve } from "node:path";
export type SearchHit={path:string;name:string;extension:string;size:number;modified_at:string;score:number;state:string};
const TEXT=new Set([".txt",".md",".csv",".tsv",".json",".yaml",".yml",".js",".jsx",".ts",".tsx",".html",".css",".xml"]);
export class SyntaxEngine{
 private db:DatabaseSync;
 constructor(public readonly dbPath:string){mkdirSync(dirname(dbPath),{recursive:true});this.db=new DatabaseSync(dbPath);this.db.exec(`PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS files(id INTEGER PRIMARY KEY,path TEXT UNIQUE,name TEXT,extension TEXT,size INTEGER,modified_at TEXT,sha256 TEXT,state TEXT DEFAULT 'CURRENT'); CREATE VIRTUAL TABLE IF NOT EXISTS files_fts USING fts5(name,path,content); CREATE TABLE IF NOT EXISTS receipts(id TEXT PRIMARY KEY,operation TEXT,status TEXT,created_at TEXT,payload TEXT);`)}
 indexFile(input:string){const path=resolve(input),s=statSync(path);if(!s.isFile())return false;const ext=extname(path).toLowerCase();if(s.size>100_000_000)return false;const bytes=readFileSync(path);let content="";if(TEXT.has(ext)&&s.size<=5_000_000)content=bytes.toString("utf8").slice(0,1_000_000);const sha=createHash("sha256").update(bytes).digest("hex");this.db.prepare(`INSERT INTO files(path,name,extension,size,modified_at,sha256,state) VALUES(?,?,?,?,?,?,'CURRENT') ON CONFLICT(path) DO UPDATE SET name=excluded.name,extension=excluded.extension,size=excluded.size,modified_at=excluded.modified_at,sha256=excluded.sha256`).run(path,basename(path),ext,s.size,s.mtime.toISOString(),sha);const family=this.db.prepare("SELECT path,name FROM files WHERE sha256=?").all(sha) as {path:string,name:string}[];const penalty=(name:string)=>{const n=name.toLowerCase();return (/(old|backup|copy|archive|superseded)/.test(n)?100:0)+(n.includes("master")?-20:0)+(n.includes("canonical")?-20:0)+name.length/1000};family.sort((a,b)=>penalty(a.name)-penalty(b.name)||a.path.localeCompare(b.path));for(const [i,file] of family.entries())this.db.prepare("UPDATE files SET state=? WHERE path=?").run(i===0?"CURRENT":"DUPLICATE",file.path);const row=this.db.prepare("SELECT id FROM files WHERE path=?").get(path) as {id:number};this.db.prepare("DELETE FROM files_fts WHERE rowid=?").run(row.id);this.db.prepare("INSERT INTO files_fts(rowid,name,path,content) VALUES(?,?,?,?)").run(row.id,basename(path),path,content);return true}
 search(query:string,limit=20):SearchHit[]{const q=query.trim().split(/\s+/).filter(Boolean).map(x=>`"${x.replace(/["']/g,"")}"*`).join(" AND ");if(!q)return[];const rows=this.db.prepare(`SELECT f.path,f.name,f.extension,f.size,f.modified_at,f.state,bm25(files_fts,8.0,2.0,1.0) rank FROM files_fts JOIN files f ON f.id=files_fts.rowid WHERE files_fts MATCH ? ORDER BY rank LIMIT ?`).all(q,limit) as any[];return rows.map((r,i)=>({...r,score:Math.max(1,Math.round(100-i*4+(r.state==="CURRENT"?0:-25))) }))}
 preset(name:string,limit=50):any[]{if(name==="master")return(this.db.prepare("SELECT path,name,extension,size,modified_at,state FROM files WHERE lower(name) LIKE '%master%' OR lower(name) LIKE '%register%' ORDER BY CASE state WHEN 'CURRENT' THEN 0 ELSE 1 END, modified_at DESC LIMIT ?").all(limit)as any[]).map((r,i)=>({...r,kind:"FILE",evidence:"LOCAL_INDEX",score:Math.max(1,100-i*3)}));if(name==="duplicates")return(this.db.prepare("SELECT path,name,extension,size,modified_at,state FROM files WHERE state='DUPLICATE' ORDER BY modified_at DESC LIMIT ?").all(limit)as any[]).map((r,i)=>({...r,kind:"FILE",evidence:"SHA_MATCH",score:Math.max(1,90-i*3)}));if(name==="receipts")return(this.db.prepare("SELECT id,operation,status,created_at,payload FROM receipts ORDER BY created_at DESC LIMIT ?").all(limit)as any[]).map((r,i)=>({name:`${r.operation} receipt`,kind:"RECEIPT",source:`receipt:${r.id}`,extension:".json",size:String(r.payload).length,modified_at:r.created_at,state:r.status,evidence:"LEDGER",score:Math.max(1,100-i)}));return[]}
 receipt(operation:string,status:string,payload:unknown,dir:string){const record={id:randomUUID(),operation,status,created_at:new Date().toISOString(),payload};this.db.prepare("INSERT INTO receipts VALUES(?,?,?,?,?)").run(record.id,operation,status,record.created_at,JSON.stringify(payload));mkdirSync(dir,{recursive:true});const target=join(dir,`${record.created_at.replaceAll(":","-")}-${operation}.json`);writeFileSync(target,JSON.stringify(record,null,2));return target}
 close(){this.db.close()}
}
